### ISSUE TITLE
Update font, font size, alignment, and spacing of "please wait" notification

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-externallinks#36]
![image](https://user-images.githubusercontent.com/5170590/33296381-315e6c56-d440-11e7-9d4c-588899bb3dd8.png)

Quick fixes to make this look better.

**Note: screenshot taken while in a JS breakpoint in my browser, so has a grey overlay. It's normally white.**

cc @clarkepaul @sachajudd

**Comment by clarkepaul** [comment]
Just to recap what I verbally said to @robbieaverill...
* Run report button would be best positioned inline with the other report actions (directly above grid area)
* The status of the report would be a notification that appeared after the report being run and possibly could also be visible when running the report with the %.
* The "Create report" button could change to use the loading indicator as it generates the report
<img width="88" alt="pasted_image_28_11_17__3_06_pm" src="https://user-images.githubusercontent.com/555033/33298928-01d45e92-d44e-11e7-9d31-a6431d70b0cf.png">

**Comment by robbieaverill** [comment]
PR to kick this off for now: https://github.com/silverstripe/silverstripe-externallinks/pull/38

I'll log a new issue to improve more in future.
