### ISSUE TITLE
Links are checked on $page->Content: won't work with modules like content blocks

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-externallinks#37]
For example if you're using a content blocks module like silverstripe-elemental, you'd want to look at the indexable search data that comes from `$page->getElementsForSearch()`.

In its current configuration the report will not work with modules that change the default content storage location from the `Content` field to anything else.

An idea for an enhancement here would be to make the HTML search locations configurable.

**Comment by robbieaverill** [comment]
This will need more thought, as the page Content field is written back to with broken link classes attached. This would mean we'd need to be inspecting content block content directly, rather than read only versions of it.

**Comment by brynwhyman** [comment]
Closing this for https://github.com/silverstripe/silverstripe-externallinks/issues/68
