### ISSUE TITLE
Broken links no longer highlighted within CMS

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-externallinks#49]
In CWP 1.8.1, using the below versions, broken links are highlighted within the CMS:
```
silverstripe/externallinks                1.1.0   
silverstripe/cms                          3.6.5             
```
See below screenshot:
![image](https://user-images.githubusercontent.com/14869519/38474138-c0e5578e-3bee-11e8-8f06-e347a3002675.png)

In CWP 2.0, using the below versions, this is no longer the case:
```
silverstripe/externallinks                2.0.x-dev 3ff01bf 
silverstripe/cms                          4.1.x-dev c6af885 
```
See below screenshot:
![image](https://user-images.githubusercontent.com/14869519/38474141-c620a9ec-3bee-11e8-8e33-f57192f95eca.png)

**Comment by robbieaverill** [comment]
Bumping priority since this is a large part of what this module is supposed to do

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-admin/pull/851

**Comment by NightJar** [comment]
Neato, nice one. But I can't merge that :<

**Comment by ScopeyNZ** [comment]
I can 🙂 . Merged.
